name: weak
description: Weak referenced collections - WeakHashMap, WeakHashSet, WeakList, and WeakReferenceQueue implemented with WeakReference and Finalizer.
version: 1.1.0
repository: https://github.com/henrichen/weak

environment:
  sdk: '>=3.2.0 <4.0.0'

dev_dependencies:
  lints: ^5.0.0
  test: any
  vm_service: any
  args: any
  logging: any